apiVersion: v1 #pod, service, configmap, secret, etc.
kind: Pod # Pod definition
metadata:
  name: demo-app # Name of the pod
  labels:
    owner: demo 
    type: frontend 
    app: demo-app # Label for the pod
spec:
  containers:
  - name: demo-app # Name of the container
    image: nginx:latest # Docker image to use
    ports:
    - containerPort: 80 # Port to expose on the container
